train_batch_size: 32
test_batch_size: 32
ratio_split_train_test: 0.1
num_workers: null
num_channels: 3
img_size: 128
device: "cuda"
num_epochs: 10
learning_rate: 0.001
momentum: 0.9
num_epochs_per_save: 2
seed: 1234
